[2019-02-17 11:53:59,695] {models.py:1359} INFO - Dependencies all met for <TaskInstance: clean.load_into_csv 2019-02-17T14:51:50.284564+00:00 [queued]>
[2019-02-17 11:53:59,697] {models.py:1359} INFO - Dependencies all met for <TaskInstance: clean.load_into_csv 2019-02-17T14:51:50.284564+00:00 [queued]>
[2019-02-17 11:53:59,697] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 2 of 2
--------------------------------------------------------------------------------

[2019-02-17 11:53:59,706] {models.py:1593} INFO - Executing <Task(PythonOperator): load_into_csv> on 2019-02-17T14:51:50.284564+00:00
[2019-02-17 11:53:59,706] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run clean load_into_csv 2019-02-17T14:51:50.284564+00:00 --job_id 5 --raw -sd /Users/brow1998/Downloads/data_engineer_etl_test/dags/first_dag.py --cfg_path /var/folders/3v/wfr8518x3q9_5f53sf2d97y00000gn/T/tmpw8u51nel']
[2019-02-17 11:54:00,597] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv [2019-02-17 11:54:00,597] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-02-17 11:54:00,967] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv [2019-02-17 11:54:00,966] {models.py:273} INFO - Filling up the DagBag from /Users/brow1998/Downloads/data_engineer_etl_test/dags/first_dag.py
[2019-02-17 11:54:01,327] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv [2019-02-17 11:54:01,327] {cli.py:520} INFO - Running <TaskInstance: clean.load_into_csv 2019-02-17T14:51:50.284564+00:00 [running]> on host bruno-macbook
[2019-02-17 11:54:01,343] {python_operator.py:95} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=clean
AIRFLOW_CTX_TASK_ID=load_into_csv
AIRFLOW_CTX_EXECUTION_DATE=2019-02-17T14:51:50.284564+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2019-02-17T14:51:50.284564+00:00
[2019-02-17 11:54:01,344] {models.py:1788} ERROR - [Errno 2] File b'/Users/brow1998/Downloads/data_engineer_etl_test/treated_data/treated_data/infomix_treated.csv' does not exist: b'/Users/brow1998/Downloads/data_engineer_etl_test/treated_data/treated_data/infomix_treated.csv'
Traceback (most recent call last):
  File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/airflow/models.py", line 1657, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 103, in execute
    return_value = self.execute_callable()
  File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 108, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/brow1998/Downloads/data_engineer_etl_test/dags/first_dag.py", line 81, in export_final_result
    infomix = pd.read_csv(treated_data/'infomix_treated.csv')
  File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'/Users/brow1998/Downloads/data_engineer_etl_test/treated_data/treated_data/infomix_treated.csv' does not exist: b'/Users/brow1998/Downloads/data_engineer_etl_test/treated_data/treated_data/infomix_treated.csv'
[2019-02-17 11:54:01,349] {models.py:1817} INFO - All retries failed; marking task as FAILED
[2019-02-17 11:54:01,367] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv Traceback (most recent call last):
[2019-02-17 11:54:01,368] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/bin/airflow", line 32, in <module>
[2019-02-17 11:54:01,369] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     args.func(args)
[2019-02-17 11:54:01,369] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-02-17 11:54:01,369] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     return f(*args, **kwargs)
[2019-02-17 11:54:01,369] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/airflow/bin/cli.py", line 526, in run
[2019-02-17 11:54:01,369] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     _run(args, dag, ti)
[2019-02-17 11:54:01,369] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/airflow/bin/cli.py", line 445, in _run
[2019-02-17 11:54:01,369] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     pool=args.pool,
[2019-02-17 11:54:01,369] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-02-17 11:54:01,369] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     return func(*args, **kwargs)
[2019-02-17 11:54:01,369] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/airflow/models.py", line 1657, in _run_raw_task
[2019-02-17 11:54:01,369] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     result = task_copy.execute(context=context)
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 103, in execute
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     return_value = self.execute_callable()
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 108, in execute_callable
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     return self.python_callable(*self.op_args, **self.op_kwargs)
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/Downloads/data_engineer_etl_test/dags/first_dag.py", line 81, in export_final_result
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     infomix = pd.read_csv(treated_data/'infomix_treated.csv')
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     return _read(filepath_or_buffer, kwds)
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     parser = TextFileReader(filepath_or_buffer, **kwds)
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     self._make_engine(self.engine)
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     self._engine = CParserWrapper(self.f, **self.options)
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "/Users/brow1998/.local/share/virtualenvs/data_engineer_etl_test-nkQxqhT3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
[2019-02-17 11:54:01,370] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv     self._reader = parsers.TextReader(src, **kwds)
[2019-02-17 11:54:01,371] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
[2019-02-17 11:54:01,371] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv   File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
[2019-02-17 11:54:01,371] {base_task_runner.py:101} INFO - Job 5: Subtask load_into_csv FileNotFoundError: [Errno 2] File b'/Users/brow1998/Downloads/data_engineer_etl_test/treated_data/treated_data/infomix_treated.csv' does not exist: b'/Users/brow1998/Downloads/data_engineer_etl_test/treated_data/treated_data/infomix_treated.csv'
[2019-02-17 11:54:04,689] {logging_mixin.py:95} INFO - [2019-02-17 11:54:04,688] {jobs.py:2527} INFO - Task exited with return code 1
